version: '3'

services:
  app:
    container_name: 'app'
    build: .
    # depends_on:
      # - mongodb
      # - redis
    env_file:
      - .env
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    networks:
      - autobot

  # redis:
  #   container_name: 'redis'
  #   image: redis:latest
  #   env_file:
  #     - .env
  #   ports:
  #     - 6379:6379
  #   restart: on-failure
  #   networks:
  #     - autobot

  # mongodb:
  #   container_name: 'mongodb'
  #   image: mongo:latest
  #   # env_file:
  #   #   - .env
  #   volumes:
  #     - ./data/mongo:/data/db
  #   ports:
  #     - "${MONGO_PORT}:${MONGO_PORT}"
  #   restart: on-failure
  #   networks:
  #     - autobot

networks:
  autobot:
