import {
  IsString,
  IsIn,
  IsDefined,
} from 'class-validator';

import {
  EBTNodeType,
} from '../models';

// TODO: nodes list at some autogenerated enum
export class NodeDto {
  @IsDefined()
  @IsString()
  @IsIn(Object.keys(EBTNodeType))
  readonly type: EBTNodeType;
}
export default NodeDto;
