import * as Joi from 'joi';

// TODO: actions list at some autogenerated enum
export const actionSchema: Joi.ObjectSchema = Joi.object({
  // type: Joi.string().valid('action').required(),
  action: Joi.object({
    fn: Joi.string()
      .valid([
        'some_test_1',
        'some_test_2',
      ])
      .required(),
  })
  .required(),
});

export default actionSchema;
