import * as Joi from 'joi';

import {
  EOperator,
} from './../models/tree/node/condition';

import {
  nodeSchema,
} from './node';

// TODO: actions list at some autogenerated enum
// TODO: HTTP OPTION request controller bot for the actions and operands enum

export enum requestParams {
  'request_param_1',
  'request_param_2',
}

export const conditionSchema: Joi.ObjectSchema = nodeSchema.keys({
  // type: Joi.string().valid('action').required(),
  condition: Joi.object({
    source: Joi.string()
      .valid(Object.keys(requestParams))
      .required(),
    target: Joi.string()
      .valid(Object.keys(requestParams))
      .required(),
    operator: Joi.string()
      .valid(Object.keys(EOperator))
      .required(),
  }).required(),
});

export default conditionSchema;
