import * as Joi from 'joi';

// TODO: nodes list at some autogenerated enum
export const nodeSchema: Joi.ObjectSchema = Joi.object({
  type: Joi.string().valid([
    'condition',
    'task',
    'sequence',
    'selector',
  ]).required(),
});

export default nodeSchema;
