import * as Joi from 'joi';

import {
  nodeSchema,
} from './node';

import {
  actionSchema,
} from './action';

// TODO: actions list at some autogenerated enum
// TODO: HTTP OPTION request controller bot for the actions and operands enum

export const taskSchema: Joi.ObjectSchema = nodeSchema.keys({
  actionSchema,
  type: Joi.string().valid('task').required(),
});

export default taskSchema;
